/**
 * Nuxt module that stamps the app version into build artifacts:
 * - public/version.json  — polled by native apps to detect updates
 * - public/sw.js          — cache name includes version so browsers detect new SW
 *
 * Both files are generated into public/ before each build so they always
 * reflect the current package.json version. They are gitignored.
 */
import { defineNuxtModule } from '@nuxt/kit'
import { writeFileSync, mkdirSync } from 'fs'
import { resolve } from 'path'

export default defineNuxtModule({
  meta: { name: 'version-stamp' },
  setup(_options, nuxt) {
    const version = process.env.npm_package_version || '0.0.0'

    // Generate before build AND on dev startup
    const generate = () => {
      const publicDir = resolve(nuxt.options.srcDir, 'public')
      mkdirSync(publicDir, { recursive: true })

      // version.json
      writeFileSync(resolve(publicDir, 'version.json'), JSON.stringify({ version }), 'utf-8')

      // sw.js with version-stamped cache name
      writeFileSync(resolve(publicDir, 'sw.js'), buildSwContent(version), 'utf-8')
    }

    nuxt.hook('build:before', generate)
    // Also generate for dev server
    nuxt.hook('app:resolve', generate)
  },
})

/**
 * @param {string} version
 * @returns {string}
 */
function buildSwContent(version) {
  return `// Auto-generated by modules/version.js — do not edit manually.
// Service worker for PWA offline support and update detection.
// Capacitor native apps skip registration (see plugins/pwa.client.js).

const CACHE_NAME = 'numori-${version}'

// App shell resources to pre-cache on install
const APP_SHELL = [
  '/',
  '/index.html',
  '/manifest.webmanifest',
  '/favicon.ico',
]

// Install: pre-cache app shell
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(APP_SHELL))
  )
})

// Activate: clean old caches and claim clients
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  )
})

// Fetch: network-first for navigations and API, cache-first for static assets
self.addEventListener('fetch', (event) => {
  const { request } = event
  const url = new URL(request.url)

  // Skip non-GET and API requests (sync, auth, etc.)
  if (request.method !== 'GET') return
  if (url.pathname.startsWith('/api/')) return
  // Never cache version.json — it must always hit the server for update detection
  if (url.pathname === '/version.json') return

  // Navigation requests: network-first with offline fallback
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const clone = response.clone()
          caches.open(CACHE_NAME).then((cache) => cache.put(request, clone))
          return response
        })
        .catch(() => caches.match('/') || caches.match('/index.html'))
    )
    return
  }

  // Static assets (_nuxt/, _fonts/, icons): cache-first
  if (url.pathname.startsWith('/_nuxt/') || url.pathname.startsWith('/_fonts/') || url.pathname.match(/\\\\.(svg|png|ico|woff2?)$/)) {
    event.respondWith(
      caches.match(request).then((cached) => {
        if (cached) return cached
        return fetch(request).then((response) => {
          if (response.ok) {
            const clone = response.clone()
            caches.open(CACHE_NAME).then((cache) => cache.put(request, clone))
          }
          return response
        }).catch(() => new Response('', { status: 503 }))
      })
    )
    return
  }

  // Everything else: network-first
  event.respondWith(
    fetch(request)
      .then((response) => {
        if (response.ok) {
          const clone = response.clone()
          caches.open(CACHE_NAME).then((cache) => cache.put(request, clone))
        }
        return response
      })
      .catch(() => caches.match(request))
  )
})

// Listen for skip-waiting message from the app
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})
`
}
